services:
  - type: web
    name: todo-app
    plan: free
    buildCommand: "./mvnw clean install"  # Ensure this command works locally
    startCommand: "java -jar target/*.jar"  # Ensure this points to the correct jar file
    branch: main
    region: oregon